# Generated by Django 4.1.6 on 2023-02-24 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_quantity', models.IntegerField(max_length=255)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('product_description', models.TextField()),
            ],
        ),
    ]
