# Generated by Django 4.1.6 on 2023-03-03 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='remedy',
            field=models.ManyToManyField(default='None', to='shop.remedy'),
        ),
    ]
