# Generated by Django 4.1.6 on 2023-03-06 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_remedy'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.TextField(blank=True, default=''),
        ),
    ]
