# Generated by Django 4.1.6 on 2023-02-24 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='product_images/default_product_image.jpg', upload_to='product_images'),
        ),
    ]
